# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-26 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='login',
        ),
    ]
